include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - public_member_api_docs: false
    - lines_longer_than_80_chars: false
    - prefer_const_constructors: true
    - prefer_const_literals_to_create_immutables: true
    - avoid_redundant_argument_values: true
    - require_trailing_commas: true
